### ISSUE TITLE
关于操作记录

### ISSUE THREAD

**Issue by SmallPiedPiper** [MonkeyOneCool/MyLogRecord#1]
咨询作者几个问题哈
1、operatorId 是怎么生成的呢 ，看样子怎么是前端带过来的参数的吗
2、操作记录的id怎么和数据库变化 联系起来，比如一个operatorId记录操作人，持久进入DB以后，然后监听到binlog日志，怎么将这两部关联起来

**Comment by ACoolMonkey** [comment]
1.我公司项目的话是会有一个全局获取operatorId的方法（通过前端传过来的token解析出来，然后放到ThreadLocal中），所以公司版本的LogRecord在operatorId配置项中只要输入“USER_INFO_ID”就可以便捷地通过调用这个方法从而获取到operatorId（当然也可以输入别的字符串获取SpEL表达式）。而现在开源出去的版本就没有这个功能了，但是完全可以自定义去实现。

2.既然你已经说到了监听binlog日志，那可以直接用canal啊，比如说canal监听到了操作人的昵称发生了变化，然后发送全局的变动消息。操作记录这里监听到消息后全局修改操作记录表里面的相关昵称（这里一种方案是全局修改之前的记录值；还有一种是不动之前的值，而是追加一条昵称从“A”改到“B”的记录；也可以完全不变化。具体是什么方案试需求而定）。
