### ISSUE TITLE
关于EnableMyLogRecordContext的设计思路

### ISSUE THREAD

**Issue by Numbk** [MonkeyOneCool/MyLogRecord#2]
首先非常感谢作者的开源分享！想要请教作者一个问题，还望赐教，不胜感激。
```java
private static final ThreadLocal<String[]> ENABLE_MY_LOG_RECORD_SCAN_BASE_PACKAGES_CACHE = new ThreadLocal<>();
```
我在学习Spring的过程中看到博主的这篇文章，阅读源码的时候对EnableMyLogRecordContext类的这个属性不是很理解，为什么这里要添加这样一个Context类进行ThreadLocal成员变量的管理。按照我的理解，LogRecordInitializer的afterPropertiesSet方法中这个Cache应该只会被执行一次吧？

既然通过@EnbaleMyLogRecord的注入链加入容器的这几个配置Bean的方法只会在启动程序的时候执行一次，为什么还需要指定该属性是ThreadLocal类型呢？

非常抱歉在此叨扰，感谢

**Comment by ACoolMonkey** [comment]
主要是为了隐性传参，将ENABLE_MY_LOG_RECORD_SCAN_BASE_PACKAGES_CACHE扫描路径的值能顺利传到LogRecordInitializer启动类中

**Comment by ACoolMonkey** [comment]
> 首先非常感谢作者的分享！想要请教作者开源一个问题，还望赐教，不胜感激。
> 
> ```java
> private static final ThreadLocal<String[]> ENABLE_MY_LOG_RECORD_SCAN_BASE_PACKAGES_CACHE = new ThreadLocal<>();
> ```
> 
> 我在学习Spring的过程中看到博主的这篇文章，阅读源码的时候对EnableMyLogRecordContext类的这个属性不太理解，为什么这里要添加这样一个Context类进行ThreadLocal成员变量的管理。按照我的理解， LogRecordInitializer的afterPropertiesSet方法中这个Cache应该只被执行一次吧？
> 
> 通过@EnbaleMyLogRecord的配置注入链加入容器的这几个Bean的方法只能在启动程序的时候执行一次，为什么还需要指定该属性是ThreadLocal类型呢？
> 
> 非常抱歉这么啰嗦，谢谢

主要是为了隐性传参，将ENABLE_MY_LOG_RECORD_SCAN_BASE_PACKAGES_CACHE扫描路径的值能顺利传到LogRecordInitializer启动类中

**Comment by Numbk** [comment]
明白了，Thx！
